### Add a New Item
POST http://localhost:5000/api/items
Content-Type: application/json

{
    "name": "Sample Item",
    "description": "This is a sample item for testing."
}

### Update an Item
PUT http://localhost:5000/api/items/66fe080bfa9da2c6a4b4cc05
Content-Type: application/json

{
    "name": "Micheal Edwards",
    "description": "this is an update"
}

### Delete an Item
DELETE http://localhost:5000/api/items/
