### Add a New Item
### Add a New Item
POST http://localhost:5000/api/items
Content-Type: application/json

{
    "name": "iphone 13 pro max",
    "description": "High-quality phone with 1TB space 6g ram.",
    "price": 1000.99,
    "category": "Electronics",
    "stock": 34,
    "brand": "iphone",
    "sku": "suk-568930"
}

### Update an Item
### Update an Existing Item
PUT http://localhost:5000/api/items/67013160d07788fecea3d75a
Content-Type: application/json

{
    "name": "iphone 13 pro max",
    "description": "High-quality phone with 1TB space 6g ram.",
    "price": 500.99,
    "category": "Electronics",
    "stock": 34,
    "brand": "iphone",
    "sku": "suk-568930"
}

### Delete an Item
DELETE http://localhost:5000/api/items/67013160d07788fecea3d75a
